[project]
name = "py-wiki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.1",
    "markdown>=3.8.2",
    "markdown2>=2.5.4",
    "ruff>=0.11.12",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
